#!/bin/sh

# green() {
#   printf "\033[32m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# red() {
#   printf "\033[31m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# yellow() {
#   printf "\033[33m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# blue() {
#   printf "\033[34m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# magenta() {
#   printf "\033[35m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# cyan() {
#   printf "\033[36m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# white() {
#   printf "\033[37m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# bold() {
#   printf "\033[1m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# underline() {
#   printf "\033[4m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# italic() {
#   printf "\033[3m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# strikethrough() {
#   printf "\033[9m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# dim() {
#   printf "\033[2m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# function blink() {
#   printf "\033[5m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# function reverse() {
#   printf "\033[7m"
#   printf "$@"
#   printf "\033[0m"
# }
#
# function hidden() {
#   printf "\033[8m"
#   printf "$@"
#   printf "\033[0m"
# }

# Simple
# read -p "Install Cmd (yay -S, pamac install, sudo apt install etc.): " install
# Colored
read -p "Install Cmd (yay -S, pamac install, sudo apt install etc.): " install


$install so-git # Stack Overflow Queries
$install perf
$install gh

read -p "Browser? (y/n): " browser
if [ "$browser" = "y" ]
then
  read -p "Binary or Source? (b/s): " bin
  if [ "$bin" = "b" ]
  then
    $install browsh-bin
  elif [ "$bin" = "s" ]
  then
    $install browsh
  fi
fi

read -p "IRC Client? (y/n): " irc
if [ "$irc" = "y" ]
then
  $install weechat # ranger is unneded (we already have an awesome file manager)
fi

read -p "Discord Client? (y/n): " discord
if [ "$discord" = "y" ]
then
  $install discordo-git # Discord Client
fi

read -p "World Map? (y/n): " map
if [ "$map" = "y" ]
then
  $install nodejs-mapscii
fi

read -p "Email Client? (y/n): " mail
if [ "$mail" = "y" ]
then
  $install mutt
fi

##############################
if command -v pipx &> /dev/null
then
  echo "pipx is installed"
  $install pipx
  # pipx install textual-paint # PAINT in your terminal
  pipx install tuir # Reddit
else
  echo "pipx is not installed"
  echo "pipx is required to install tuir (Reddit)"
  echo "Do you want to install pipx?"
  read -p "y/n: " pipx
  if [ $pipx = "y" ]
  then
    $install pipx
    # pipx install textual-paint # PAINT in your terminal
    pipx install tuir # Reddit
  else
    echo "Skipping pipx installation"
  fi
fi
##############################

# See: https://seniormars.github.io/posts/neomutt/#motivation
# $instally neomutt # an email client
# $instally gnupg # TODO: Still in WIP.



# # Create a key and follow the instructions that are prompted:
# gpg --full-generate-key
#
# # Copy your public key:
# gpg --list-secret-keys --keyid-format=long
#
# # FIX: Unable to open mailbox /var/spool/mail/$USER
# sudo touch /var/mail/$USER
# sudo chown $USER:mail /var/mail/$USER
# sudo chmod 660 /var/mail/$USER
#
# pipx install urlscan

# gh extension install dlvhdr/gh-dash # Octo is preferred over gh dash

# NOTE: These cool block comments are generated by built-in snippets <3

#######################
#        CARGO        #
#######################

if command -v cargo &> /dev/null
then
  echo "cargo could not be found"
  echo "Cargo is required to install Hacker News TUI"
  echo "Do you want to install cargo?"
  read -p "y/n: " rustup
  if [ "$rustup" = "y" ]
  then
      $install cargo
      # Hacker News TUI
      cargo install hackernews_tui
  else
    echo "Skipping Hacker News TUI installation"
    exit
  fi
fi

#######################################
#        ORGMODE DOC GENERATOR        #
#######################################
# $install pandoc
